import { Connection, PublicKey } from "@solana/web3.js";
import { AnchorProvider, Program, Idl } from "@coral-xyz/anchor";
import type { AnchorWallet } from "@solana/wallet-adapter-react";

// IDL will be generated by `arcium build` — import it at runtime
// For now, we define the program setup utilities

const PROGRAM_ID = new PublicKey(
    process.env.NEXT_PUBLIC_PROGRAM_ID ??
    "PrivPerps1111111111111111111111111111111111"
);

const RPC_URL =
    process.env.NEXT_PUBLIC_RPC_URL ?? "https://api.devnet.solana.com";

/** Create a Solana connection to devnet */
export function getConnection(): Connection {
    return new Connection(RPC_URL, {
        commitment: "confirmed",
        confirmTransactionInitialTimeout: 120_000,
    });
}

/** Create an Anchor provider from a wallet adapter */
export function getProvider(wallet: AnchorWallet): AnchorProvider {
    const connection = getConnection();
    return new AnchorProvider(connection, wallet, {
        preflightCommitment: "confirmed",
        commitment: "confirmed",
    });
}

/** Get the program instance — requires the IDL to be loaded */
export function getProgram(
    wallet: AnchorWallet,
    idl: Idl
): Program {
    const provider = getProvider(wallet);
    return new Program(idl, PROGRAM_ID, provider);
}

/** Derive the global state PDA */
export function getGlobalStatePda(): PublicKey {
    const [pda] = PublicKey.findProgramAddressSync(
        [Buffer.from("global_state")],
        PROGRAM_ID
    );
    return pda;
}

/** Derive a position PDA for a given owner and position index */
export function getPositionPda(
    owner: PublicKey,
    positionIndex: number
): PublicKey {
    const indexBuf = Buffer.alloc(8);
    indexBuf.writeBigUInt64LE(BigInt(positionIndex));
    const [pda] = PublicKey.findProgramAddressSync(
        [Buffer.from("position"), owner.toBuffer(), indexBuf],
        PROGRAM_ID
    );
    return pda;
}

export { PROGRAM_ID, RPC_URL };
